project:
  type: website
  output-dir: docs

website:
  title: "irridiumhzt.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - About.qmd
      text: About


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

