---
title: "NM2207 Final Project"
---

With Pink tourism on the rise, Europe is fast becoming one of the most popular travel destinations in the world. With higher purchasing power and willingness to spend, they could help to generate more revenues for the host countries. According to a survey conducted in the U.S. by Harris Interactive, LGBT adults report that on average they intended to spend $1300 between May and August 2021 for leisure, while the average planned expenditure is $1058. As such, being perceived as LGBT friendly would be a huge pulling factor for attracting LGBT tourists.

In addition, I believe the public tends to discriminate even within LGBT community, making life worse for the non-binary and transgender minority in the group, as they are disproportionately targeted in hate crimes. According to the FBI's Hate Crime Statistics, transgender individuals, particularly transgender women of colour, are at a higher risk of experiencing violent hate crimes in the United States. I would like to investigate to what extent this is true in Europe.


**Data Mutation**
Using the dataset on Kaggle [https://www.kaggle.com/datasets/ruslankl/european-union-lgbt-survey-2012/data], 
I have carried out Data Mutation to make sure that the data are not affected by small sample size.
For rows, the ones labelled with [0] and [1] for notes would be avoided, since they correspond to NA and  small sample size, and thus not statistically relevant. 


    
**All things considered, how satisfied would you say you are with your life these days**

```{=html}
<iframe height="400" width="100%" frameborder="no" src="https://irridiumhzt.shinyapps.io/Chart/"> </iframe>


```


**Conclusion**

Overall, the three most LGBT friendly countries in EU are Luxembourg, the Netherlands, and Denmark.
For Gay men, the most friendly country in EU is Luxembourg.
For Lesbian women, the most friendly country in EU is the Netherlands.
For Bisexual men, the most friendly country in EU is the Netherlands.
For Bisexual women, the most friendly country in EU is the Austria.
For Transgender individuals, the most friendly country is the Spain.